# Generated by Django 4.0.1 on 2022-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at_alter_post_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional Author Bio. Separate From Professional Profile Resume Summary and Object', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, help_text='Input the main body of text (aka the main content)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Input the main body of text (aka the main content)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(help_text='Add a brief summary to show as a preview of the main content', max_length=155),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title for this contentto be used as the headline', max_length=200),
        ),
    ]
