# Generated by Django 4.0.1 on 2022-02-18 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=155, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField(null=True)),
                ('highlights', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('credential', models.CharField(max_length=255, null=True)),
                ('secondary_credentials', models.TextField(max_length=500, null=True)),
                ('url', models.URLField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interpersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What do you call this skill? What do you type in to google, to find information about this skill?', max_length=155, null=True)),
                ('proficiency_level', models.CharField(choices=[('N', 'Novice'), ('P', 'Proficient'), ('E', 'Expert')], default='P', help_text="This field will NOT be public. It's solely for sorting skills (desc) from most proficient to least proficient as to emphasize the skills that you are most comfortable interviewing in.", max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=155, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField(null=True)),
                ('highlights', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What do you call this skill? What do you type in to google, to find information about this skill?', max_length=155, null=True)),
                ('proficiency_level', models.CharField(choices=[('N', 'Novice'), ('P', 'Proficient'), ('E', 'Expert')], default='P', help_text="This field will NOT be public. It's solely for sorting skills (desc) from most proficient to least proficient as to emphasize the skills that you are most comfortable interviewing in.", max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=155, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField(null=True)),
                ('highlights', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(null=True)),
                ('resume_summary', models.TextField(null=True)),
                ('public_email', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
