# Generated by Django 4.0.1 on 2022-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interpersonal',
            options={'verbose_name': 'SoftSkill', 'verbose_name_plural': 'SoftSkills'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'HardSkill', 'verbose_name_plural': 'HardSkills'},
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='resume_link',
            field=models.TextField(help_text='Upload your resume to Google Drive and Share the File with anyone who has the link. Copy and Paste the link into this field', null=True),
        ),
    ]
