# Generated by Django 4.0.1 on 2022-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_interpersonal_options_alter_technical_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpersonal',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='technical',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.AlterField(
            model_name='educational',
            name='credential',
            field=models.CharField(help_text='Enter Credentials here. Degrees, Certifications, Licenses, Diplomas, Etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='educational',
            name='highlights',
            field=models.TextField(help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='institution',
            field=models.CharField(help_text='Name of the Company, Organization, University, Website, Institution, Chairty, Establishment (and or etc)', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='location',
            field=models.TextField(help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent.', null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='overview',
            field=models.TextField(help_text='Basic Summary of what you did there', null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='secondary_credentials',
            field=models.TextField(help_text='Enter related course, certificates, or minor credentials that are related to the input above. IE a Minor in Pyschology', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='start_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='educational',
            name='url',
            field=models.URLField(help_text='This field is meant for certifications and other credentials that offer a url to validate the credential', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interpersonal',
            name='proficiency_level',
            field=models.CharField(choices=[('N', 'Novice'), ('C', 'Competent'), ('P', 'Proficient'), ('E', 'Expert')], default='P', help_text='(Private Field Only) The Input from this field is used to sort your skills by how comfortable you are, interviewing in them. No one will know what level you enter, other than you. Skills will be sorted, most proficient to least proficient as to emphasize the skills that you are the best at.\nNovice = Beginner, \nCompetent = Beginner to Intermediate, \nProficient = Intermediate to Advanced, \nExpert = Advanced to Mastery', max_length=1),
        ),
        migrations.AlterField(
            model_name='professional',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='highlights',
            field=models.TextField(help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='institution',
            field=models.CharField(help_text='Name of the Company, Organization, University, Website, Institution, Chairty, Establishment (and or etc)', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='location',
            field=models.TextField(help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent.', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='overview',
            field=models.TextField(help_text='Basic Summary of what you did there', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='start_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='title',
            field=models.CharField(help_text='Job Title or Professional Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='objective',
            field=models.TextField(help_text='(Optional) Resume Objective, generally found at the top of a resume/cv.', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='public_email',
            field=models.TextField(help_text='(Recommended) Enter the email employers should contact you at. This will be public and can be different from the signup email if you so choose.', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='resume_link',
            field=models.TextField(help_text='(Recommended) Upload your resume to Google Drive and Share the File with anyone who has the link. Copy and Paste the link into this field', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='resume_summary',
            field=models.TextField(help_text='(Optional) Resume Summary Section', null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='proficiency_level',
            field=models.CharField(choices=[('N', 'Novice'), ('C', 'Competent'), ('P', 'Proficient'), ('E', 'Expert')], default='P', help_text='(Private Field Only) The Input from this field is used to sort your skills by how comfortable you are, interviewing in them. No one will know what level you enter, other than you. Skills will be sorted, most proficient to least proficient as to emphasize the skills that you are the best at.\nNovice = Beginner, \nCompetent = Beginner to Intermediate, \nProficient = Intermediate to Advanced, \nExpert = Advanced to Mastery', max_length=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='highlights',
            field=models.TextField(help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='institution',
            field=models.CharField(help_text='Name of the Company, Organization, University, Website, Institution, Chairty, Establishment (and or etc)', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.TextField(help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent.', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='overview',
            field=models.TextField(help_text='Basic Summary of what you did there', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='start_date',
            field=models.DateTimeField(auto_now=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
    ]
