# Generated by Django 4.0.1 on 2022-02-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_name_interpersonal_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educational',
            options={'verbose_name': 'Education/Certification', 'verbose_name_plural': 'Education/Certification'},
        ),
        migrations.AlterModelOptions(
            name='interpersonal',
            options={'verbose_name': 'Soft Skill', 'verbose_name_plural': 'Soft Skills'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Professional Experience', 'verbose_name_plural': 'Professional Experience'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'Hard Skill', 'verbose_name_plural': 'Hard Skills'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Volunteer Experience', 'verbose_name_plural': 'Volunteer Experience'},
        ),
    ]
