# Generated by Django 4.0.1 on 2022-02-18 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0004_alter_educational_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interpersonal',
            options={'verbose_name': 'Interpersonal/Soft Skill', 'verbose_name_plural': 'Interpersonal/Soft Skills'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'Technical/Hard Skill', 'verbose_name_plural': 'Technical/Hard Skills'},
        ),
        migrations.RemoveField(
            model_name='educational',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='institution',
        ),
        migrations.AddField(
            model_name='educational',
            name='institution_name',
            field=models.CharField(help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='institution_name',
            field=models.CharField(help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='institution_name',
            field=models.CharField(help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='end_date',
            field=models.DateField(help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='educational',
            name='location',
            field=models.CharField(blank=True, help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent. Typically, Location is not relavent and this field can be left blank.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='start_date',
            field=models.DateField(help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='interpersonal',
            name='proficiency_level',
            field=models.CharField(choices=[('N', 'Novice'), ('B', 'Advanced Beginner'), ('C', 'Competent'), ('P', 'Proficient'), ('E', 'Expert')], default='C', help_text='(Private Field Only) The Input from this field is used to sort your skills on your resume related pages. The names of each level-choice option will not be featured publically.\n        \nNo one will know what level a skill was set at, other than the person who entered it (you).\n        \nSkills will be ordered by most proficient to least proficient as to emphasize the skills that you are the most confident about.\n        \nNovice is the most beginner level while Expert level represents Mastery.\n        \nBe Honest with yourself on these. Think about how confident you would be recieving a blind interview that involves using the skill.', max_length=1),
        ),
        migrations.AlterField(
            model_name='interpersonal',
            name='skill_name',
            field=models.CharField(help_text='Label / Name of the skill. IE "Critical Thinking", "Microsoft Office", "Django", "Leadership", etc. ', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='end_date',
            field=models.DateField(help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='location',
            field=models.CharField(blank=True, help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent. Typically, Location is not relavent and this field can be left blank.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='start_date',
            field=models.DateField(help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='objective',
            field=models.TextField(blank=True, help_text='(Optional) Resume Objective, generally found at the top of a resume/cv.', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='public_email',
            field=models.CharField(blank=True, help_text='(Recommended) Enter the email employers should contact you at. This will be public and can be different from the signup email if you so choose.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='resume_link',
            field=models.TextField(blank=True, help_text='(Recommended) Upload your resume to Google Drive and Share the File with anyone who has the link. Copy and Paste the link into this field', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='resume_summary',
            field=models.TextField(blank=True, help_text='(Optional) Resume Summary Section', null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technical',
            name='proficiency_level',
            field=models.CharField(choices=[('N', 'Novice'), ('B', 'Advanced Beginner'), ('C', 'Competent'), ('P', 'Proficient'), ('E', 'Expert')], default='C', help_text='(Private Field Only) The Input from this field is used to sort your skills on your resume related pages. The names of each level-choice option will not be featured publically.\n        \nNo one will know what level a skill was set at, other than the person who entered it (you).\n        \nSkills will be ordered by most proficient to least proficient as to emphasize the skills that you are the most confident about.\n        \nNovice is the most beginner level while Expert level represents Mastery.\n        \nBe Honest with yourself on these. Think about how confident you would be recieving a blind interview that involves using the skill.', max_length=1),
        ),
        migrations.AlterField(
            model_name='technical',
            name='skill_name',
            field=models.CharField(help_text='Label / Name of the skill. IE "Critical Thinking", "Microsoft Office", "Django", "Leadership", etc. ', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateField(help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(blank=True, help_text='(Optional) Meant for professional fields (IE Job and etc) or Institutions where location is relavent. Typically, Location is not relavent and this field can be left blank.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='start_date',
            field=models.DateField(help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored'),
        ),
    ]
