# Generated by Django 4.0.1 on 2022-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_interpersonal_options_alter_technical_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='educational',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='start_date',
        ),
        migrations.AddField(
            model_name='educational',
            name='end',
            field=models.DateField(blank=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AddField(
            model_name='educational',
            name='start',
            field=models.DateField(blank=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='end',
            field=models.DateField(blank=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='start',
            field=models.DateField(blank=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='end',
            field=models.DateField(blank=True, help_text='Input Month / Year of last day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='start',
            field=models.DateField(blank=True, help_text='Input Month / Year of first day (Day can be set to whatever, it will be ignored', null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='highlights',
            field=models.TextField(blank=True, help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='educational',
            name='overview',
            field=models.TextField(blank=True, help_text='Basic Summary of what you did there', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='highlights',
            field=models.TextField(blank=True, help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='overview',
            field=models.TextField(blank=True, help_text='Basic Summary of what you did there', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='highlights',
            field=models.TextField(blank=True, help_text='Achievements, awards, and other notable details to highlight/emphasize', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Name of the Company, Organization, University, School, Buisness, Website, Institution, Chairty, Establishment, etc.', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='overview',
            field=models.TextField(blank=True, help_text='Basic Summary of what you did there', null=True),
        ),
    ]
