# Generated by Django 4.0.1 on 2022-01-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('L', 'Literature'), ('VA', 'Visual Arts'), ('GA', 'Graphic Arts'), ('PLA', 'Plastic Arts'), ('DA', 'Decorative Arts'), ('PFA', 'Performing Arts'), ('M', 'Music'), ('ARC', 'Architecture')], help_text='\n         This is just a general guide, feel free to use the categories however you wish.\n         Here is an explanation of the Categories:\n         Literature = including poetry, drama, story, and so on.\n         Visual Arts = painting, drawing, sculpture, etc.\n         Graphic Arts = painting, drawing, design, and other forms expressed on flat surfaces\n         Plastic Arts = sculpture, modeling.\n         Decorative Arts = enamelwork, furniture design, mosaic, etc.\n         Performing Arts = theatre, dance, music.\n         Music = composition, sound.\n         Architecture = includes interior design\n         ', max_length=3),
        ),
    ]
