# Generated by Django 4.0.1 on 2022-01-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_link_project_media_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='secondary',
            field=models.CharField(help_text='Secondary Category for the project. Define a more specific grouping here.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('L', 'Literature'), ('VA', 'Visual Arts'), ('GA', 'Graphic Arts'), ('PLA', 'Plastic Arts'), ('DA', 'Decorative Arts'), ('PFA', 'Performing Arts'), ('M', 'Music'), ('ARC', 'Architecture')], help_text="\n         <i>This is a general guide, feel free to use the categories however you wish.</i>\n         <br> The Categories will be used to split up portfolio sections based on art type.\n         <br>\n         <br>Explanation of the Named Categories:<br>\n            <br>(Literature) = including poetry, drama, story, and so on.\n            <br>(Visual Arts) = painting, drawing, sculpture, etc.\n            <br>(Graphic Arts) = painting, drawing, design, and other forms expressed on flat surfaces.\n            <br>(Plastic Arts) = sculpture, modeling, etc.\n            <br>(Decorative Arts) = enamelwork, furniture design, mosaic, etc.\n            <br>(Performing Arts) = theatre, dance, music.\n            <br>(Music) = composition, sound, and so on.\n            <br>(Architecture) = includes interior design.\n            <br>\n            <br><i>If a category doesn't quite feel right, choose the closet category and add the more suitable category name as a tag.</i>\n         ", max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=255),
        ),
    ]
