# Generated by Django 4.0.1 on 2022-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='body',
            field=models.CharField(editable=False, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
