# Generated by Django 4.0.1 on 2022-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contact_body_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text="Elements (or Element titles) are the Titles of Resume Sections. \nIE 'Education', 'Experience', 'Objective', and etc. \nNew Sections can be entered here if the one you'd like to include, does not already exist. \nTIP: You can check to see if it exists by creating a new Resume Section object", max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('head', models.CharField(max_length=75, null=True)),
                ('summary', models.TextField(max_length=500, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('section', models.ManyToManyField(related_name='me', to='about.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
