# Generated by Django 4.0.1 on 2022-02-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_category_resume_delete_contact_delete_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='section',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
