# Generated by Django 4.0.1 on 2022-02-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('about', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_date',
        ),
        migrations.CreateModel(
            name='ActiveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
