# Generated by Django 4.0.1 on 2022-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('skill', models.CharField(max_length=20)),
                ('image', models.FilePathField(null=True, path='/media/img')),
                ('sound', models.FilePathField(null=True, path='/media/audio')),
                ('video', models.FilePathField(null=True, path='/media/vid')),
            ],
        ),
    ]
