# Generated by Django 4.0.1 on 2022-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sound',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FilePathField(null=True),
        ),
    ]
