# Generated by Django 4.0.1 on 2022-02-13 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_skill_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your URL something meaningful. This field is public.', max_length=255)),
                ('info', models.TextField(help_text='Add a Short Description for this URL. This field is public.', null=True)),
                ('url', models.URLField(max_length=1000, unique=True, validators=[django.core.validators.URLValidator(message='Enter a valid URL - must be unqiue.')])),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(help_text='Copy and Paste the url to the external content you want to include', null=True, to='projects.Link'),
        ),
    ]
