# Generated by Django 4.0.1 on 2022-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_link_project_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_content', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_content',
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(help_text='Copy and Paste the url to the external content you want to include', to='projects.Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='uploads',
            field=models.ManyToManyField(help_text='Upload the Content to use with this project post and to store in memory.', to='projects.Content'),
        ),
    ]
