# Generated by Django 4.0.1 on 2022-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_links_remove_project_uploads_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='project_content',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='content',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='content_upload',
            field=models.ManyToManyField(help_text='Upload the Content to use with this project post and to store in memory.', related_name='project_content', to='projects.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='info',
            field=models.TextField(blank=True, help_text='Add a Short Description for this URL. This field is public.', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(help_text='Name your URL something meaningful. This field is public.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='projects',
            field=models.ManyToManyField(help_text='Copy and Paste the url to the external content you want to include', related_name='content_link', to='projects.Project'),
        ),
    ]
