# Generated by Django 4.0.1 on 2022-02-18 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_project_content_content_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='info',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.RemoveField(
            model_name='link',
            name='projects',
        ),
        migrations.AddField(
            model_name='link',
            name='label',
            field=models.CharField(help_text='Website Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(help_text='Copy and Paste the url to the external content you want to include', related_name='projects', to='projects.Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1000, unique=True, validators=[django.core.validators.URLValidator(message='Enter a valid (unqiue) URL')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=155),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
