# Generated by Django 4.0.1 on 2022-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_link_alt_alter_link_label_alter_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_upload',
            field=models.ManyToManyField(blank=True, help_text='Upload the Content to use with this project post and to store in memory. \nUploading media content does not work through the administration panel.', related_name='project_content', to='projects.Content'),
        ),
    ]
