# Generated by Django 4.0.1 on 2022-02-21 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_upload',
        ),
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
