# Generated by Django 4.0.1 on 2022-02-21 19:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_content_upload_remove_project_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
