# Generated by Django 4.0.1 on 2022-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('L', 'Literature'), ('VA', 'Visual Arts'), ('GA', 'Graphic Arts'), ('PLA', 'Plastic Arts'), ('DA', 'Decorative Arts'), ('PFA', 'Performing Arts'), ('M', 'Music'), ('ARC', 'Architecture')], help_text="\n         This is just a general guide, feel free to use the categories however you wish.\n         If a category doesn't quite feel right, choose the closet category and add the more suitable category name as a tag.\n         Here is an explanation of the Named Categories:\n            (Literature) = including poetry, drama, story, and so on.\n            (Visual Arts) = painting, drawing, sculpture, etc.\n            (Graphic Arts) = painting, drawing, design, and other forms expressed on flat surfaces.\n            (Plastic Arts) = sculpture, modeling, etc.\n            (Decorative Arts) = enamelwork, furniture design, mosaic, etc.\n            (Performing Arts) = theatre, dance, music.\n            (Music) = composition, sound, and so on.\n            (Architecture) = includes interior design.\n         ", max_length=3),
        ),
    ]
